default: &default
  adapter: postgresql
  host: 127.0.0.1
  username: postgres
  #username: johnbeynon
  #password: amnesia99
  
development:
  database: bankr_development
  <<: *default

test:
  database: bankr_test
  <<: *default